# Generated by Django 3.1.7 on 2021-03-08 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individuo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_core.individuo_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('individuo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.individuo')),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.individuo',),
        ),
        migrations.CreateModel(
            name='Bem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('valor', models.FloatField()),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.individuo')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('individuo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.individuo')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('donos', models.ManyToManyField(related_name='donos', to='core.Individuo')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('core.individuo',),
        ),
    ]
